version: "3.5"

services:
  mdbook:
    command: serve --hostname '0.0.0.0'
    image: peaceiris/mdbook:v0.4.30-rust
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ".:/book"
    container_name: mdbook
